import FancyboxBinder from '@/components/FancyboxBinder'
import Footer from '@/components/footer/Footer'
import Header from '@/components/header/Header'
import PageTransition from '@/components/ui/PageTransition'
import { getHeader } from '@/services/header.service'
import { getSiteSetting } from '@/services/site-setting.service'
import { mapSiteSetting } from '@/utils/site-setting.mapper'
import '@fancyapps/ui/dist/fancybox/fancybox.css'
import '@fontsource-variable/noto-serif'
import '@fontsource-variable/roboto-slab'
import '@fontsource/yeseva-one'
import { AnimatePresence } from 'framer-motion'
import type { Metadata } from 'next'
import { ReactNode } from 'react'
import './globals.css'
import './swiper.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: ReactNode
}>) {
	const siteSettingResponse = await getSiteSetting()
	const siteSetting = mapSiteSetting(siteSettingResponse)

	// Загружаем header с обработкой ошибок
	let headerData = null
	try {
		headerData = await getHeader()
	} catch (error) {
		console.error('Ошибка при загрузке header в layout:', error)
		// Продолжаем работу без header данных - компонент сам обработает fallback
	}

	return (
		<html lang='ru' data-theme='cupcake'>
			<head>
				{siteSetting.favicon && (
					<link rel='icon' href={siteSetting.favicon} type='image/svg+xml' />
				)}
				{siteSetting.appleFavicon && (
					<link rel='apple-touch-icon' href={siteSetting.appleFavicon} />
				)}
			</head>
			<body>
				<FancyboxBinder />
				<AnimatePresence>
					<PageTransition>
						<Header headerData={headerData || undefined} />
						{children}
						<Footer />
					</PageTransition>
				</AnimatePresence>
			</body>
		</html>
	)
}
